# Generated by Django 4.0.4 on 2022-06-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0002_alter_expenses_count_alter_expenses_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useramount',
            name='my_expense',
        ),
    ]
