# Generated by Django 4.0.4 on 2022-06-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0003_remove_useramount_my_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='useramount',
            name='expenses',
            field=models.ManyToManyField(to='expense_tracker_app.expenses'),
        ),
    ]
