# Generated by Django 4.0.4 on 2022-06-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0005_remove_expenses_count_useramount_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useramount',
            name='expenses',
        ),
        migrations.AddField(
            model_name='expenses',
            name='who_paid',
            field=models.ManyToManyField(related_name='expenses', to='expense_tracker_app.useramount'),
        ),
    ]
