# Generated by Django 4.0.4 on 2022-06-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_app', '0006_remove_useramount_expenses_expenses_who_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useramount',
            name='count',
        ),
        migrations.AddField(
            model_name='expenses',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
