# Generated by Django 4.0.4 on 2022-05-31 16:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='TodoApp',
        ),
        migrations.RenameField(
            model_name='todoapp',
            old_name='title',
            new_name='task',
        ),
    ]
