# Generated by Django 4.0.4 on 2022-06-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_todoapp_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoapp',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
