# Generated by Django 4.0.4 on 2022-06-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_todoapp_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='task',
            field=models.CharField(max_length=200),
        ),
    ]
