# Generated by Django 4.0.4 on 2022-06-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_alter_calendarapp_author_alter_calendarapp_for_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarapp',
            name='data_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
