# Generated by Django 4.0.4 on 2022-06-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_calendarapp_data_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarapp',
            name='task',
            field=models.CharField(max_length=200),
        ),
    ]
