# Generated by Django 4.0.4 on 2022-06-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_alter_calendarapp_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarapp',
            name='created',
        ),
    ]
