# Generated by Django 4.0.4 on 2022-06-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_remove_calendarapp_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarapp',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
