# Generated by Django 4.0.4 on 2022-06-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_rename_data_added_calendarapp_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarapp',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
