# Generated by Django 4.0.4 on 2022-06-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0008_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
