# Generated by Django 4.0.4 on 2022-06-13 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0009_comments_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='date_added',
        ),
    ]
