# Generated by Django 4.0.4 on 2022-06-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0010_remove_comments_date_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
