# Generated by Django 4.0.4 on 2022-06-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0012_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarapp',
            name='recurrent',
            field=models.IntegerField(default=0),
        ),
    ]
